// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
#include "ui.h"
#include "ui_font_profile.h"
#include "ui_helpers.h"
#include "ui_home_runtime.h"
#include "ui_runtime_common.h"

#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <driver/gpio.h>

#include "bsp_obd_dsp/boards/board_api.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "esp_system.h"

static const char *TAG = "ui";
static bool s_logo_transition_started = false;

#define UI_NAV_ANIM_MS 200
#define UI_NAV_ANIM_LOGO_MS 300

static const char *gesture_dir_name(lv_dir_t dir)
{
    switch (dir) {
    case LV_DIR_LEFT:
        return "LEFT";
    case LV_DIR_RIGHT:
        return "RIGHT";
    case LV_DIR_TOP:
        return "TOP";
    case LV_DIR_BOTTOM:
        return "BOTTOM";
    default:
        return "NONE";
    }
}

static void log_gesture_event(const char *screen_name, lv_dir_t dir)
{
    ESP_LOGI(TAG, "%s gesture=%s", screen_name, gesture_dir_name(dir));
}

static void ui_logo_unloaded_cb(lv_event_t *e)
{
    lv_obj_t *screen = lv_event_get_target(e);
    ESP_LOGI(TAG, "Logo unloaded: screen=%p active_now=%p", (void *)screen, (void *)lv_scr_act());
    if (screen != NULL) {
        lv_obj_del(screen);
    }
    ui_ScreenPageLogo = NULL;
    imageLogo = NULL;
}

static void ui_logo_transition_to(lv_obj_t **target_scr, void (*target_init)(void), const char *reason)
{
    if (s_logo_transition_started) {
        ESP_LOGI(TAG, "Logo transition ignored: reason=%s already started", reason);
        return;
    }

    s_logo_transition_started = true;
    ESP_LOGI(TAG, "Logo transition start: reason=%s logo=%p target_ptr=%p target=%p",
             reason,
             (void *)ui_ScreenPageLogo,
             (void *)target_scr,
             target_scr ? (void *)(*target_scr) : NULL);

    if (ui_ScreenPageLogo != NULL) {
        lv_obj_add_event_cb(ui_ScreenPageLogo, ui_logo_unloaded_cb, LV_EVENT_SCREEN_UNLOADED, NULL);
    }

    _ui_screen_change(target_scr, LV_SCR_LOAD_ANIM_FADE_ON, UI_NAV_ANIM_LOGO_MS, 0, target_init);
}

///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t *ui_ScreenPageLogo;
lv_obj_t *imageLogo;

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t *ui_ScreenPageBLEScan;

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t *ui_ScreenPageSettings;

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
lv_obj_t *ui_ScreenPageODBProtocal;
lv_obj_t *ui_SpinnerODBProtocalEgg;
lv_obj_t *ui_ArcPageODBProtocalBack;
lv_obj_t *ui_RollerODBProtocalChoose;
lv_obj_t *ui_ImageODBProtocalBlackEar;
lv_obj_t *ui_LabelOBDIIText;
lv_obj_t *ui_LabelSureTipText;

// EVENTS
lv_obj_t *ui____initial_actions0;

static uint16_t usSaveProtTimeCnt = 0;

// IMAGES AND IMAGE SETS
#define CLEAR_TRIP_TIME 2000
#define SAVE_PROTOCOL_TIME 2000

void my_timerMain(lv_timer_t *timer)
{
    LV_UNUSED(timer);
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    ui_legacy_runtime_tick(ui_ScreenPageLogo != NULL);

    if (ucOnlyOnce == 0) {
        ulOpenLightTimeCnt++;
        if (ulOpenLightTimeCnt > 400 / 200) {
            const nvs_user_cfg_t *bl_cfg = nvs_cfg_get();
            uint8_t bright = bl_cfg->brightness_day;
            esp_err_t err;

            if (bright < 10) {
                bright = 100;
            }
            err = board_set_brightness(bright);
            if (err != ESP_OK) {
                ESP_LOGW(TAG, "Set display brightness failed: %s", esp_err_to_name(err));
            } else {
                ESP_LOGI(TAG, "Set display brightness to %d%%", bright);
            }
            ulOpenLightTimeCnt = 0;
            ucOnlyOnce = 1;
        }
    }

    if (ui_ScreenPageLogo) {
        static uint32_t ulLogoTimeCnt = 0;

        ulLogoTimeCnt++;
        if (ulLogoTimeCnt > 3000 / 200) {
            const nvs_user_cfg_t *pg_cfg = nvs_cfg_get();
            lv_obj_t **target_scr = &ui_ScreenPageHome;
            void (*target_init)(void) = ui_home_runtime_screen_init;

            ulLogoTimeCnt = 0;
            ui_home_runtime_reset(ui_home_runtime_page_from_default(pg_cfg->default_page));
            if (*target_scr == NULL) {
                target_init();
            }
            ui_logo_transition_to(target_scr, target_init, "timeout");
            ui_legacy_runtime_on_logo_exit();
        }
    }
}

void ui_event_logo_background(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t click_cnt = 0;
        uint32_t now = lv_tick_get();

        if (now - last_click_tick < 400) {
            click_cnt++;
        } else {
            click_cnt = 1;
        }
        last_click_tick = now;

        if (click_cnt >= 2) {
            click_cnt = 0;
            if(ui_ScreenPageODBProtocal == NULL) ui_ScreenPageODBProtocal_screen_init();
            ui_logo_transition_to(&ui_ScreenPageODBProtocal, ui_ScreenPageODBProtocal_screen_init, "double_click");
        }
    }
}

void ui_label_set_text_if_changed(lv_obj_t *label, const char *text)
{
    const char *current;

    if (!label || !text) {
        return;
    }

    current = lv_label_get_text(label);
    if (current != NULL && strcmp(current, text) == 0) {
        return;
    }

    lv_label_set_text(label, text);
}

void ui_label_set_text_fmt_if_changed(lv_obj_t *label, const char *fmt, ...)
{
    char buf[128];
    va_list args;

    if (!label || !fmt) {
        return;
    }

    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    ui_label_set_text_if_changed(label, buf);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp;
    lv_theme_t *theme;

    ui_font_profile_init();
    dispp = lv_disp_get_default();
    theme = lv_theme_default_init(dispp,
                                  lv_palette_main(LV_PALETTE_BLUE),
                                  lv_palette_main(LV_PALETTE_RED),
                                  false,
                                  LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    ui_home_runtime_reset(ui_home_runtime_page_from_default(nvs_cfg_get()->default_page));
    ui_ScreenPageODBProtocal = NULL;
    ui____initial_actions0 = lv_obj_create(NULL);
    s_logo_transition_started = false;
    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_create(my_timerMain, 200, NULL);
}

void ui_event_obd_prot_background(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());

        log_gesture_event("OBDProtocal", dir);
        if (dir == LV_DIR_TOP) {
            ESP_LOGI(TAG,
                     "OBDProtocal gesture: return to home active_before=%p",
                     (void *)lv_scr_act());
            lv_indev_wait_release(lv_indev_get_act());
            ui_home_runtime_show_page(ui_home_runtime_page_from_default(nvs_cfg_get()->default_page),
                                      LV_SCR_LOAD_ANIM_MOVE_TOP);
            ESP_LOGI(TAG, "OBDProtocal gesture: switch requested active_after=%p", (void *)lv_scr_act());
        }
    } else if (code == LV_EVENT_LONG_PRESSED) {
        usSaveProtTimeCnt = 0;
    } else if (code == LV_EVENT_LONG_PRESSED_REPEAT) {
        usSaveProtTimeCnt += 100;
        if (usSaveProtTimeCnt >= SAVE_PROTOCOL_TIME / 100) {
            nvs_user_cfg_t cfg = *nvs_cfg_get();

            usSaveProtTimeCnt = 0;
            cfg.protocol = lv_roller_get_selected(ui_RollerODBProtocalChoose);
            nvs_cfg_set(&cfg);
            esp_restart();
        }
    } else if (code == LV_EVENT_RELEASED) {
        usSaveProtTimeCnt = 0;
    }
}
