// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
#include "ui.h"
#include "ui_font_profile.h"
#include "ui_helpers.h"
#include "ui_home_runtime.h"
#include "ui_runtime_common.h"

#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <driver/gpio.h>

#include "bsp_obd_dsp/boards/board_api.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "esp_system.h"

static const char *TAG = "ui";
static bool s_logo_transition_started = false;

#define UI_NAV_ANIM_MS 0
#define UI_WAIT_BRIGHTNESS_BURST_COUNT 3u
#define UI_WAIT_BRIGHTNESS_BURST_LOW_PCT 30u
#define UI_WAIT_BRIGHTNESS_BURST_ON_TICKS 1u
#define UI_WAIT_BRIGHTNESS_BURST_OFF_TICKS 1u

static void ui_apply_waiting_brightness_pulse(void);

/**
 * Tear down the splash screen once it is no longer active.
 *
 * Core responsibility: delete logo screen objects only after LVGL
 * confirms the screen transition has fully completed.
 */
static void ui_logo_unloaded_cb(lv_event_t *e)
{
    lv_obj_t *screen = lv_event_get_target(e);
    if (screen != NULL) {
        lv_obj_del(screen);
    }
    ui_ScreenPageLogo = NULL;
    imageLogo = NULL;
}

/**
 * Transition away from the splash logo exactly once.
 *
 * Core responsibility: guard against duplicate exit paths so timeout
 * and user-driven transitions cannot both destroy the same screen.
 */
static void ui_logo_transition_to(lv_obj_t **target_scr, void (*target_init)(void), const char *reason)
{
    if (s_logo_transition_started) {
        LV_UNUSED(reason);
        return;
    }

    s_logo_transition_started = true;

    if (ui_ScreenPageLogo != NULL) {
        lv_obj_add_event_cb(ui_ScreenPageLogo, ui_logo_unloaded_cb, LV_EVENT_SCREEN_UNLOADED, NULL);
    }

    _ui_screen_change(target_scr, LV_SCR_LOAD_ANIM_NONE, 0, 0, target_init);
}

///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t *ui_ScreenPageLogo;
lv_obj_t *imageLogo;

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t *ui_ScreenPageBLEScan;

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t *ui_ScreenPageSettings;

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
#define CLEAR_TRIP_TIME 2000

/**
 * Periodic UI heartbeat timer.
 *
 * Core responsibilities: handle deferred backlight setup, tick legacy
 * runtime hooks, and leave the logo page after its display timeout.
 */
void my_timerMain(lv_timer_t *timer)
{
    LV_UNUSED(timer);
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    ui_legacy_runtime_tick(ui_ScreenPageLogo != NULL);

    // ========== DEFERRED BACKLIGHT ==========
    // Wait a short time before pushing brightness so panel power-up
    // completes first and the first setting write is not ignored.
    if (ucOnlyOnce == 0) {
        ulOpenLightTimeCnt++;
        if (ulOpenLightTimeCnt > 400 / 200) {
            const nvs_user_cfg_t *bl_cfg = nvs_cfg_get();
            uint8_t bright = bl_cfg->brightness_day;
            esp_err_t err;

            if (bright < 10) {
                bright = 100;
            }
            err = board_set_brightness(bright);
            if (err != ESP_OK) {
                ESP_LOGW(TAG, "Set display brightness failed: %s", esp_err_to_name(err));
            } else {
                ESP_LOGI(TAG, "Set display brightness to %d%%", bright);
            }
            ulOpenLightTimeCnt = 0;
            ucOnlyOnce = 1;
        }
    }

    ui_apply_waiting_brightness_pulse();

    // ========== SPLASH EXIT ==========
    // The home screen is prepared before switching so the splash can
    // disappear without a blank intermediate frame.
    if (ui_ScreenPageLogo) {
        static uint32_t ulLogoTimeCnt = 0;

        ulLogoTimeCnt++;
        if (ulLogoTimeCnt > 3000 / 200) {
            const nvs_user_cfg_t *pg_cfg = nvs_cfg_get();
            lv_obj_t **target_scr = &ui_ScreenPageHome;
            void (*target_init)(void) = ui_home_runtime_screen_init;

            ulLogoTimeCnt = 0;
            ui_home_runtime_reset(ui_home_runtime_page_from_default(pg_cfg->default_page));
            if (*target_scr == NULL) {
                target_init();
            }
            ui_logo_transition_to(target_scr, target_init, "timeout");
            ui_legacy_runtime_on_logo_exit();
        }
    }
}

static void ui_apply_waiting_brightness_pulse(void)
{
    static bool s_wait_pulse_active = false;
    static uint8_t s_last_applied_brightness = 0xFF;
    static uint8_t s_wait_burst_tick = 0u;
    static uint8_t s_wait_burst_count = 0u;
    const nvs_user_cfg_t *cfg = nvs_cfg_get();
    uint8_t base_brightness = cfg->brightness_day;
    uint8_t pulse_brightness = base_brightness;
    bool waiting_for_first_data;

    if (base_brightness < 10u) {
        base_brightness = 100u;
    }

    waiting_for_first_data = (ui_ScreenPageLogo == NULL) &&
                             (ui_runtime_sweep_step_get() == 0) &&
                             elm327_ble_is_waiting_for_first_valid_payload();

    if (waiting_for_first_data) {
        uint8_t burst_cycle_ticks = UI_WAIT_BRIGHTNESS_BURST_ON_TICKS + UI_WAIT_BRIGHTNESS_BURST_OFF_TICKS;
        uint8_t dim_brightness =
            (uint8_t)((uint32_t)base_brightness * UI_WAIT_BRIGHTNESS_BURST_LOW_PCT / 100u);

        if (dim_brightness >= base_brightness) {
            dim_brightness = (base_brightness > 1u) ? (uint8_t)(base_brightness - 1u) : 0u;
        }

        if (!s_wait_pulse_active) {
            s_wait_burst_tick = 0u;
            s_wait_burst_count = 0u;
        }

        if (s_wait_burst_count < UI_WAIT_BRIGHTNESS_BURST_COUNT) {
            if (s_wait_burst_tick < UI_WAIT_BRIGHTNESS_BURST_ON_TICKS) {
                pulse_brightness = dim_brightness;
            } else {
                pulse_brightness = base_brightness;
            }

            s_wait_burst_tick++;
            if (s_wait_burst_tick >= burst_cycle_ticks) {
                s_wait_burst_tick = 0u;
                s_wait_burst_count++;
            }
        } else {
            pulse_brightness = dim_brightness;
        }

        s_wait_pulse_active = true;
    } else {
        pulse_brightness = base_brightness;
        s_wait_burst_tick = 0u;
        s_wait_burst_count = 0u;
        s_wait_pulse_active = false;
    }

    if (pulse_brightness == s_last_applied_brightness) {
        return;
    }

    if (board_set_brightness(pulse_brightness) == ESP_OK) {
        s_last_applied_brightness = pulse_brightness;
    } else if (s_wait_pulse_active) {
        ESP_LOGW(TAG, "Waiting brightness pulse update failed");
    }
}

/** 生成代码里 Logo 背景控件的占位事件回调。 */
void ui_event_logo_background(lv_event_t *e)
{
    LV_UNUSED(e);
}

/**
 * Update a label only when the text actually changed.
 *
 * Core responsibility: avoid redundant LVGL work on fast refresh
 * paths where the same value may be emitted every cycle.
 */
void ui_label_set_text_if_changed(lv_obj_t *label, const char *text)
{
    const char *current;

    if (!label || !text) {
        return;
    }

    current = lv_label_get_text(label);
    if (current != NULL && strcmp(current, text) == 0) {
        return;
    }

    lv_label_set_text(label, text);
}

/**
 * Format label text and skip the update when the result is unchanged.
 *
 * Core responsibility: give refresh code one formatted update helper
 * without forcing a redraw for identical string content.
 */
void ui_label_set_text_fmt_if_changed(lv_obj_t *label, const char *fmt, ...)
{
    char buf[128];
    va_list args;

    if (!label || !fmt) {
        return;
    }

    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    ui_label_set_text_if_changed(label, buf);
}

///////////////////// SCREENS ////////////////////

/**
 * Initialize the generated UI and load the first screen.
 *
 * Core responsibilities: initialize fonts and theme, prepare the
 * home runtime state, create the splash page, and start the UI timer.
 */
void ui_init(void)
{
    lv_disp_t *dispp;
    lv_theme_t *theme;

    ui_font_profile_init();
    dispp = lv_disp_get_default();
    theme = lv_theme_default_init(dispp,
                                  lv_palette_main(LV_PALETTE_BLUE),
                                  lv_palette_main(LV_PALETTE_RED),
                                  false,
                                  LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    ui_home_runtime_reset(ui_home_runtime_page_from_default(nvs_cfg_get()->default_page));
    ui____initial_actions0 = lv_obj_create(NULL);
    s_logo_transition_started = false;
    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_create(my_timerMain, 200, NULL);
}
