// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#ifndef _OBD_PRJ_UI_H
#define _OBD_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_home_runtime.h"
#include "ui_events.h"
#include "esp_log.h"
#include "app_obd_dsp/obd_data_cache.h"

#define USE_GIF_LOGO        0
#define USE_GIF_EASTER_EGG  0

#define COLOR_MITSUBISHI_RED    0xFFFFFF //主色调白色(原三菱红)
#define COLOR_DOMIANT_PINK      0xFFFFFF //主色调白色(原粉色)
#define COLOR_SECONDARY_PINK    0x333333 //副色调深灰(原暗粉)



void ui_ScreenPageLogo_screen_init(void);
extern lv_obj_t * ui_ScreenPageLogo;
extern lv_obj_t * imageLogo;

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
extern lv_obj_t * ui_ScreenPageODBProtocal;
extern lv_obj_t * ui_SpinnerODBProtocalEgg;
extern lv_obj_t * ui_ArcPageODBProtocalBack;
extern lv_obj_t * ui_RollerODBProtocalChoose;
extern lv_obj_t * ui_ImageODBProtocalBlackEar;
extern lv_obj_t * ui_LabelOBDIIText;
extern lv_obj_t * ui_LabelSureTipText;

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
extern lv_obj_t * ui_ScreenPageBLEScan;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
extern lv_obj_t * ui_ScreenPageSettings;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;
LV_IMG_DECLARE(gifBlueLightLogo);    
LV_IMG_DECLARE(gifSnake400);  
LV_IMG_DECLARE(gifKaBiBaLaZip);    // assets/pngBlueLightLogo.png
LV_IMG_DECLARE(gifCuteCatZip);
LV_IMG_DECLARE(gifBlackLeopard);
// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pngmainback_png);    // assets/pngMainBack.png
LV_IMG_DECLARE(pngLogoMITSUBISHI);    // assets/pngLogoMITSUBISHI.png
LV_IMG_DECLARE(pngLogoSkyGarage);     // assets/sklogo.png (280x280)
LV_IMG_DECLARE(ui_img_pngblackear_png);    // assets/pngBlackEar.png
// FONTS
LV_FONT_DECLARE(ui_font_FontBabyGearNumSize48);
LV_FONT_DECLARE(ui_font_FontBabySize108);
LV_FONT_DECLARE(ui_font_FontBabySize156);
LV_FONT_DECLARE(ui_font_FontBabySize180);
LV_FONT_DECLARE(ui_font_FontBabySize200);
LV_FONT_DECLARE(ui_font_FontBabySize56);
LV_FONT_DECLARE(ui_font_FontTaikongSize108);
LV_FONT_DECLARE(ui_font_FontTaikongSize128);
LV_FONT_DECLARE(ui_font_FontTaikongSize32);
LV_FONT_DECLARE(ui_font_FontTaikongSize40);
LV_FONT_DECLARE(ui_font_FontTaikongSize48);
LV_FONT_DECLARE(ui_font_FontTaikongSize56);
LV_FONT_DECLARE(ui_font_FontTaikongSize64);
LV_FONT_DECLARE(ui_font_FontTaikongSize72);
LV_FONT_DECLARE(ui_font_FontTypoderSize16);
LV_FONT_DECLARE(ui_font_FontTypoderSize20);
LV_FONT_DECLARE(ui_font_FontTypoderSize24);
LV_FONT_DECLARE(ui_font_FontTypoderSize28);
LV_FONT_DECLARE(ui_font_FontTypoderSize32);
LV_FONT_DECLARE(ui_font_FontTypoderSize36);
LV_FONT_DECLARE(ui_font_FontTypoderSize40);
LV_FONT_DECLARE(ui_font_FontTypoderSize44);
LV_FONT_DECLARE(ui_font_FontTypoderSize56);
LV_FONT_DECLARE(ui_font_FontTypoderSize100);
LV_FONT_DECLARE(ui_font_FontTypoderSize140);


// UI INIT
void ui_init(void);
void ui_event_logo_background(lv_event_t * e);
void ui_event_obd_prot_background(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
