#ifndef UI_DEBUG_CONFIG_H
#define UI_DEBUG_CONFIG_H

#define UI_DEBUG_VALUE_MOCK_ENABLED 0
#define UI_DEBUG_METRIC_LAYOUT_LOG_ENABLED 0
#define UI_DEBUG_GEAR_PAGE_FORCE_RPM_ENABLED 0
#define UI_DEBUG_GEAR_PAGE_FORCE_RPM_VALUE 9000u

#define UI_DEBUG_SAMPLE_TEXT_TEMP     "999"
#define UI_DEBUG_SAMPLE_TEXT_LOAD     "100"
#define UI_DEBUG_SAMPLE_TEXT_RPM      "9999"
#define UI_DEBUG_SAMPLE_TEXT_SPEED    "999"
#define UI_DEBUG_SAMPLE_TEXT_BAT      "99.9"
#define UI_DEBUG_SAMPLE_TEXT_PRESSURE "99.9"
#define UI_DEBUG_SAMPLE_TEXT_BOOST    "-99.9"

#define UI_DEBUG_MOCK_TEMP_VALUE_C       999
#define UI_DEBUG_MOCK_LOAD_VALUE_PCT     100
#define UI_DEBUG_MOCK_RPM_VALUE          9999
#define UI_DEBUG_MOCK_SPEED_VALUE_KMH    999
#define UI_DEBUG_MOCK_BAT_VALUE_MV       99900
#define UI_DEBUG_MOCK_PRESSURE_VALUE_X10 999

#endif
